FIXED_LAT = 5000

NUM_NODES = 100
ADV_NID = -10000 # No adversary miner
TXN_INTERARRIVAL = 5000*5
MINING_TIME = 20*FIXED_LAT*NUM_NODES
SIM_TIME = 200*(MINING_TIME/NUM_NODES)

#For Regenesis
NUM_ACC_BAL_PER_BLOCK = 50
MAX_LENGTH_BLOCKCHAIN = 20
EMPTY_BLOCKS_LENGTH = 3

MINING_FEE = 50

ADV_PEER_FRAC = 0.75
ADV_TYPE = "selfish"

# MINING_TIME_OF_NETWORK = MINING_TIME / NUM_NODES