FIXED_LAT = 50

NUM_NODES = 60
ADV_NID = -10000 # No adversary miner
TXN_INTERARRIVAL = FIXED_LAT*3  
MINING_TIME = 15*FIXED_LAT*NUM_NODES
SIM_TIME = 100*(MINING_TIME/NUM_NODES)

#For Regenesis
NUM_ACC_BAL_PER_BLOCK = 20
MAX_LENGTH_BLOCKCHAIN = 30
EMPTY_BLOCKS_LENGTH = 5

MINING_FEE = 50

ADV_PEER_FRAC = 0.75
ADV_TYPE = "selfish"

# MINING_TIME_OF_NETWORK = MINING_TIME / NUM_NODES